### ISSUE TITLE
docker-compose -f example/cluster-hostname.yaml up 

### ISSUE THREAD

**Issue by 13539956066** [nacos-group/nacos-docker#12]
fbb8790129fe        nacos/nacos-server:latest         "bin/docker-startu..."   19 minutes ago      Restarting (1) 3 minutes ago                                                    nacos3
0a82822739e1        nacos/nacos-server:latest         "bin/docker-startu..."   19 minutes ago      Up 18 minutes                  0.0.0.0:8849->8848/tcp                           nacos2
89c28a08da28        nacos/nacos-server:latest         "bin/docker-startu..."   19 minutes ago      Up 18 minutes                  0.0.0.0:8848->8848/tcp, 0.0.0.0:9555->9555/tcp   nacos1

nacos3          | + JAVA_MAJOR_VERSION=1
nacos3          | + [[ 1 -ge 9 ]]
nacos3          | + JAVA_OPT=' -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -Xdebug -Xrunjdwp:transport=dt_socket,address=9555,server=y,suspend=n -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb'
nacos3          | + JAVA_OPT=' -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -Xdebug -Xrunjdwp:transport=dt_socket,address=9555,server=y,suspend=n -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M'
nacos3          | + [[ hostname == \h\o\s\t\n\a\m\e ]]
nacos3          | + JAVA_OPT=' -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -Xdebug -Xrunjdwp:transport=dt_socket,address=9555,server=y,suspend=n -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.preferHostnameOverIp=true'

docker-compose 创建有　nacos 　有一个应用没能启用。
是不是我的电脑内存不够吗。

**Comment by paderlol** [comment]
你能贴出nacos-3的日志吗? 日志应该在example目录里面能看到的

**Comment by 13539956066** [comment]
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                         PORTS                                            NAMES
fbb8790129fe        nacos/nacos-server:latest         "bin/docker-startu..."   19 minutes ago      Restarting (1) 3 minutes ago                                                    nacos3
0a82822739e1        nacos/nacos-server:latest         "bin/docker-startu..."   19 minutes ago      Up 18 minutes                  0.0.0.0:8849->8848/tcp                           nacos2
89c28a08da28        nacos/nacos-server:latest         "bin/docker-startu..."   19 minutes ago      Up 18 minutes                  0.0.0.0:8848->8848/tcp, 0.0.0.0:9555->9555/tcp   nacos1


[root@VM_0_9_centos /]# docker start fbb8790129fe

[root@VM_0_9_centos /]# docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                        PORTS                    NAMES
fbb8790129fe        nacos/nacos-server:latest         "bin/docker-startu..."   40 minutes ago      Up 5 seconds                  0.0.0.0:8850->8848/tcp   nacos3
0a82822739e1        nacos/nacos-server:latest         "bin/docker-startu..."   40 minutes ago      Exited (137) 19 minutes ago                            nacos2
89c28a08da28        nacos/nacos-server:latest         "bin/docker-startu..."   40 minutes ago      Exited (137) 19 minutes ago                            nacos1
我直接当个启动
其它两个应用就关掉了

**Comment by 13539956066** [comment]
我直接启动干才那个应用 fbb8790129fe 原为这个应用就是 nacos3
执行  docker start fbb8790129fe

执行当个启动后。其它两个应用自动就关掉。

**Comment by paderlol** [comment]
你可以把nacos 的运行日志贴上来吗？ example/cluster-log下面应该有运行的日志 这样可能会比较好分析一点,方便的话最好把你机器的配置也发下.

**Comment by 13539956066** [comment]
2019-01-23 17:03:55,621 WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'communicationController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-0.8.0.jar!/com/alibaba/nacos/config/server/controller/CommunicationController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set

2019-01-23 17:03:55,625 INFO Stopping service [Tomcat]

2019-01-23 17:03:55,636 WARN The web application [nacos] appears to have started a thread named [nacos.naming.status.worker] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)

2019-01-23 17:03:55,636 WARN The web application [nacos] appears to have started a thread named [nacos.naming.domains.worker] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)

2019-01-23 17:03:55,637 WARN The web application [nacos] appears to have started a thread named [nacos.naming.domains.update.processor] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
 java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
 com.alibaba.nacos.naming.core.DomainsManager$UpdatedDomainProcessor.run(DomainsManager.java:140)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)

2019-01-23 17:03:55,637 WARN The web application [nacos] appears to have started a thread named [nacos.naming.init.config.worker] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 java.lang.Thread.sleep(Thread.java:340)
 java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
 com.alibaba.nacos.naming.core.DomainsManager.initConfig(DomainsManager.java:94)
 com.alibaba.nacos.naming.core.DomainsManager.access$500(DomainsManager.java:44)
 com.alibaba.nacos.naming.core.DomainsManager$3.run(DomainsManager.java:607)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)

2019-01-23 17:03:55,642 INFO Nacos Log files: /home/nacos/logs/

2019-01-23 17:03:55,643 INFO Nacos Conf files: /home/nacos/conf/

2019-01-23 17:03:55,643 INFO Nacos Data files: /home/nacos/data/

2019-01-23 17:03:55,643 ERROR Nacos failed to start, please see /home/nacos/logs/nacos.log for more details.

2019-01-23 17:03:55,656 INFO 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2019-01-23 17:03:55,661 ERROR Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'communicationController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-0.8.0.jar!/com/alibaba/nacos/config/server/controller/CommunicationController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.alibaba.nacos.Nacos.main(Nacos.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1237)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 27 common frames omitted
Caused by: java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at com.alibaba.nacos.config.server.service.dump.DumpService.init(DumpService.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 40 common frames omitted
2019-01-23 17:03:59,107 INFO The server IP list of Nacos is [nacos1:8848, nacos2:8848, nacos3:8848]

2019-01-23 17:03:59,133 INFO Starting Nacos v0.8.0 on nacos3 with PID 20 (/home/nacos/target/nacos-server.jar started by root in /home/nacos)

2019-01-23 17:03:59,135 INFO No active profile set, falling back to default profiles: default

2019-01-23 17:04:00,113 INFO Nacos is starting...

2019-01-23 17:04:01,117 INFO Nacos is starting...

2019-01-23 17:04:02,073 INFO Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$befa284f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-01-23 17:04:02,117 INFO Nacos is starting...

2019-01-23 17:04:02,206 INFO Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-01-23 17:04:02,209 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@20b5f2ac' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-01-23 17:04:02,213 INFO Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$e3cecb01] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-01-23 17:04:02,220 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-01-23 17:04:02,909 INFO Tomcat initialized with port(s): 8848 (http)

2019-01-23 17:04:02,931 INFO Initializing ProtocolHandler ["http-nio-8848"]

2019-01-23 17:04:02,951 INFO Starting service [Tomcat]

2019-01-23 17:04:02,951 INFO Starting Servlet Engine: Apache Tomcat/9.0.13

2019-01-23 17:04:02,967 INFO The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]

2019-01-23 17:04:03,089 INFO Initializing Spring embedded WebApplicationContext

2019-01-23 17:04:03,089 INFO Root WebApplicationContext: initialization completed in 3853 ms

**Comment by 13539956066** [comment]
日记比较大 服务器  2cpu 4g内 _centos 7.4

**Comment by 13539956066** [comment]
我把日记打包上传

**Comment by paderlol** [comment]
你是不是数据库没有启动成功? 日志里面错误是说你没有找到数据库,你可以尝试把container 全部停掉,然后使用这个命令启动一次
```shell
docker-compose -f cluster-host.yaml up
```
可以在控制台看到启动的过程

**Comment by paderlol** [comment]
> [myfile.zip](https://github.com/nacos-group/nacos-docker/files/2786540/myfile.zip)

我这边看了日志,猜测两种可能性：
 1. docker 第一次启动的时候会依赖于数据库的启动,所以会正常出现restarting的情况,也是正常的
 2. 确实你本机的内存不够导致的,不过这个要你自己确认下是不是内存导致的

**Comment by LauItachi** [comment]
我这边遇到防火墙的问题访问不到同服务器中用docker部署的主从MySQL，放通端口之后可以访问了
```sh
firewall-cmd --permanent --zone=public --add-port=3306/tcp --add-port=3307/tcp
firewall-cmd --reload
```
一开始以为内存不够去kill了其他服务，但是还是跑不起来，没想到最后竟然是栽在防火墙上……（主要是一开始本机用workbench可以正常连通就认为不用放防火墙，没想到它连内部人员都不放过[有内鬼 交易终止 /手动狗头]）
