### ISSUE TITLE
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up

### ISSUE THREAD

**Issue by jelen56** [nacos-group/nacos-docker#142]
-Explain:
> Before install nacos,there is a mysql8.0 running in my docker.and i want to use this container(mysql8.0) as a database for nacos. and i met this problem when i tried several time to run nacos-docker
# Here is the error log and my configuration files.
## Error log:
```javascript
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:905)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:830)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
	at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl$SelectMasterTask.run(ExternalDataSourceServiceImpl.java:233)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)
	... 24 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
	... 26 common frames omitted
```

##  Configuration files
- env/nacos-standlone-mysql.env(**mysql8.0 is my mysql container name**)：
```javascript
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=mysql8.0
MYSQL_SERVICE_DB_NAME=nacos
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=nacos
MYSQL_SERVICE_PASSWORD=nacos
NACOS_AUTH_ENABLE=true
NACOS_AUTH_TOKEN_EXPIRE_SECONDS=36000
```
- example/standalone-mysql-8.yaml：
```javascript
version: "2"
services:
  nacos:
    image: nacos/nacos-server:1.4.0-BETA
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    external_links:
      - mysql:8.0
    restart: always
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure
networks:
  default:
    external:
      name: net-docker
```
- build/conf/application.properties（**add "&serverTimezone=GMT%2B8" to db.url**）：
```javascript

# spring
server.servlet.contextPath=${SERVER_SERVLET_CONTEXTPATH:/nacos}
server.contextPath=/nacos
server.port=${NACOS_APPLICATION_PORT:8848}
spring.datasource.platform=${SPRING_DATASOURCE_PLATFORM:""}
nacos.cmdb.dumpTaskInterval=3600
nacos.cmdb.eventTaskInterval=10
nacos.cmdb.labelTaskInterval=300
nacos.cmdb.loadDataAtStart=false
db.num=${MYSQL_DATABASE_NUM:1}
db.url.0=jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?${MYSQL_SERVICE_DB_PARAM:characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=GMT%2B8}
db.url.1=jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?${MYSQL_SERVICE_DB_PARAM:characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=GMT%2B8}
db.user=${MYSQL_SERVICE_USER}
db.password=${MYSQL_SERVICE_PASSWORD}
### The auth system to use, currently only 'nacos' is supported:
nacos.core.auth.system.type=${NACOS_AUTH_SYSTEM_TYPE:nacos}


### The token expiration in seconds:
nacos.core.auth.default.token.expire.seconds=${NACOS_AUTH_TOKEN_EXPIRE_SECONDS:18000}

### The default token:
nacos.core.auth.default.token.secret.key=${NACOS_AUTH_TOKEN:SecretKey012345678901234567890123456789012345678901234567890123456789}

### Turn on/off caching of auth information. By turning on this switch, the update of auth information would have a 15 seconds delay.
nacos.core.auth.caching.enabled=${NACOS_AUTH_CACHE_ENABLE:false}

server.tomcat.accesslog.enabled=${TOMCAT_ACCESSLOG_ENABLED:false}
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
# default current work dir
server.tomcat.basedir=
## spring security config
### turn off security
nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**
# metrics for elastic search
management.metrics.export.elastic.enabled=false
management.metrics.export.influx.enabled=false
nacos.naming.distro.taskDispatchThreadCount=10
nacos.naming.distro.taskDispatchPeriod=200
nacos.naming.distro.batchSyncKeyCount=1000
nacos.naming.distro.initDataRatio=0.9
nacos.naming.distro.syncRetryDelay=5000
nacos.naming.data.warmup=true
```
- example/init.d/custom.properties：
```javascript
spring.security.enabled=true
management.security=true
security.basic.enabled=true
nacos.security.ignore.urls=/,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/login,/v1/console/health/**,/v1/cs/**,/v1/ns/**,/v1/cmdb/**,/actuator/**,/v1/console/server/**
#management.metrics.export.elastic.host=http://localhost:9200
# metrics for prometheus
management.endpoints.web.exposure.include=*

# metrics for elastic search
#management.metrics.export.elastic.enabled=false
#management.metrics.export.elastic.host=http://localhost:9200

# metrics for influx
#management.metrics.export.influx.enabled=false
#management.metrics.export.influx.db=springboot
#management.metrics.export.influx.uri=http://localhost:8086
#management.metrics.export.influx.auto-create-db=true
#management.metrics.export.influx.consistency=one
#management.metrics.export.influx.compressed=true
```

## Code branch:
```javascript
git clone -b 1.4.0 git@github.com:nacos-group/nacos-docker.git
```

## The process of executing instructions(no error)：
```javascript
docker network create net-docker --driver bridge
docker network connect net-docker mysql8.0
```
```javascript
[xxxx@localhost nacos-docker]# docker-compose -f example/standalone-mysql-8.yaml up -d
Creating nacos-standalone-mysql ... done
Creating grafana                ... done
Creating prometheus             ... done

```

## Enter container command mode and find that there are only three files in conf folder(**without nacos-mysql.sql**)：
```javascript
[xxxx@localhost nacos-docker]# docker exec -it nacos-standalone-mysql bash
[xxxx@5179ab84b0b4 nacos]# cd conf/ &&ll
total 40
-rw-r--r--. 1 xxxx xxxx   2232 Oct 23 18:02 application.properties
-rw-r--r--. 1  502 games 25715 Oct 22 14:59 nacos-logback.xml
-rw-r--r--. 1  502 games  8073 Oct 16 09:23 schema.sql
```

## About docker network：
- net-docker:
```javascript
[xxxxx@localhost nacos-docker]# docker network inspect net-docker 
[
    {
        "Name": "net-docker",
        "Id": "f68a31fdd2c7287a13a12b29f014dddab30641a758cc366a7d3f2f291365ca03",
        "Created": "2020-11-17T12:04:07.347541114+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "5179ab84b0b4ec5f0e013f8738f847345481ce0ac5d61dc2380facd879e24780": {
                "Name": "nacos-standalone-mysql",
                "EndpointID": "b82196698a3b70c03f871a090082959e73b85109e46c4bd8da40b3629e8d9a44",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
            "5f55e26df2eeb2499372b03159235d72d203774cf528dbfe1c343c0b889bd94e": {
                "Name": "prometheus",
                "EndpointID": "80842e30947ca931c74dd3ce93947df3dcecb3394a9e7525b4c9ce32ce8c9522",
                "MacAddress": "02:42:ac:13:00:05",
                "IPv4Address": "172.19.0.5/16",
                "IPv6Address": ""
            },
            "704dc6e85dfcf009f0af8b7fe433bab6e1105a286caf87a1d472042b478ca587": {
                "Name": "mysql8.0",
                "EndpointID": "14c28921a43f0e1b286359f83b476c9adf7c65bb65fc60d8432781d95fdc93e7",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "99a4bc131acb0fe5cf968d272dabbcaf3f2c686d131950d077f3dc4cdb0de603": {
                "Name": "grafana",
                "EndpointID": "b14690a66adef24f63eeda0001e992d83b162378e7205f261f3e0454c7d389fd",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```
- containers ping result:
```javascript
[xxxx@localhost nacos-docker]# docker exec nacos-standalone-mysql ping mysql8.0 
PING mysql8.0 (172.19.0.2) 56(84) bytes of data.
64 bytes from mysql8.0.net-docker (172.19.0.2): icmp_seq=1 ttl=64 time=0.078 ms
64 bytes from mysql8.0.net-docker (172.19.0.2): icmp_seq=2 ttl=64 time=0.138 ms
64 bytes from mysql8.0.net-docker (172.19.0.2): icmp_seq=3 ttl=64 time=0.048 ms
64 bytes from mysql8.0.net-docker (172.19.0.2): icmp_seq=4 ttl=64 time=0.140 ms
64 bytes from mysql8.0.net-docker (172.19.0.2): icmp_seq=5 ttl=64 time=0.133 ms
64 bytes from mysql8.0.net-docker (172.19.0.2): icmp_seq=6 ttl=64 time=0.142 ms
```
## The driver for mysql is newest:
![nacos-sever.jar](https://i.loli.net/2020/11/19/PcTqviKnVXerb6k.png)

### My guess is that docker compose fail to build “nacos-standalone-mysql” container when building container, because I didn't see MySQL initialization script(nacos-mysql.sql) in conf folder after build-task done, but I don't know why,could you take the time to help me take a look,thx.

**Comment by paderlol** [comment]
You need to initialize the database script yourself

**Comment by jelen56** [comment]
> You need to initialize the database script yourself, The example description is because I repackaged it. If it is your own copy, you need to initialize the Nacos database script in the database by yourself, including creating tables.
> 
> https://github.com/alibaba/nacos/blob/develop/distribution/conf/nacos-mysql.sql

Yes, I did as you said, but the problem still exist
![nacos db](https://i.loli.net/2020/11/19/TVgvE8hkXeoQbJ9.png)

**Comment by paderlol** [comment]
I tried to reproduce your problem, but I found that it is normal here, and your error did not appear. You need to look at your own database connection or permission related issues

``` yaml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:1.4.0-BETA
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    external_links:
      - 892f1c8cad3a
    restart: always

```

``` 
// env code
MYSQL_SERVICE_HOST=892f1c8cad3a

``` 

![image](https://user-images.githubusercontent.com/7919984/99638038-a5286300-2a80-11eb-9c63-0f5f7b661854.png)

**Comment by yszansx** [comment]
Candidate problems appear in the cluster. Single node can be used normally.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nacos-group/nacos-docker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 下午4:03
收件人:&nbsp;"nacos-group/nacos-docker"<nacos-docker@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [nacos-group/nacos-docker] java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up (#142)





 
I tried to reproduce your problem, but I found that it is normal here, and your error did not appear. You need to look at your own database connection or permission related issues
 version: "2" services:   nacos:     image: nacos/nacos-server:1.4.0-BETA     container_name: nacos-standalone-mysql     env_file:       - ../env/nacos-standlone-mysql.env     volumes:       - ./standalone-logs/:/home/nacos/logs       - ./init.d/custom.properties:/home/nacos/init.d/custom.properties     ports:       - "8848:8848"       - "9555:9555"     external_links:       - 892f1c8cad3a     restart: always 
 // env code MYSQL_SERVICE_HOST=892f1c8cad3a

**Comment by czy1024** [comment]
I also have the same problem, a single node can cluster in the same network segment has been unable to connect to the database, I use Windows has been able to connect to the MySQL

**Comment by paderlol** [comment]
In the cluster. This problem may occur when initializing database image for the first time. Just restart it

**Comment by czy1024** [comment]
> In the cluster. This problem may occur when initializing database image for the first time. Just restart it

Just restart the container? docker restart nacos1 nacos2 nacos3

**Comment by paderlol** [comment]
`docker-compose -f yaml restart`

**Comment by czy1024** [comment]
> `docker-compose -f yaml restart`

Sorry, this does not work, but the mysql data I started with this script is also effective on the windows cluster. It is still this error when accessed in the container.

**Comment by paderlol** [comment]
I can work on both mac and ubuntu systems. You may need to check the database-related errors or your docker network problems yourself

**Comment by czy1024** [comment]
Okay, thank you. Only cluster-hostname.yaml is needed. Have you modified other configurations?

**Comment by paderlol** [comment]
There are no other modifications

**Comment by czy1024** [comment]
> There are no other modifications

Thank you for your reminder. I can work after reinstalling the system, and customizing the docker bridge network is also possible. The current guess may be a network problem caused by the previous installation of the pagoda panel.

**Comment by ydxdx201** [comment]
我使用的数据库是5.7.25，db.url后面也追加了&useUnicode=true&useSSL=false&serverTimezone=UTC，但是还是报数据库连接失败，启动的时候是正常的，就是运行一段时间后就会出现这个问题

**Comment by jelen56** [comment]
> > There are no other modifications
> 
> Thank you for your reminder. I can work after reinstalling the system, and customizing the docker bridge network is also possible. The current guess may be a network problem caused by the previous installation of the pagoda panel.

This should be a network or firewall configuration problem, and I finally solved the problem by modifying the related configuration

**Comment by 1798972** [comment]
我之前也是用自己的mysql8跑的nacos，还运行了一段时间，所以配置是没有问题的。
定位到是docker的问题，今天出问题后进入nacos容器，发现nacos和mysql网络突然不通了，重启docker解决的。
