### ISSUE TITLE
standalone-mysql-5.7 nacos用户没用自动赋予权限

### ISSUE THREAD

**Issue by toolsqacn** [nacos-group/nacos-docker#149]
在Ubuntu 20.04 上使用standalone-mysql-5.7.yaml 搭建单机环境。MySQL数据库连接总是报错：
```
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
	at
```
查看用户权限发现，nacos用户权限没有自动初始化。赋予用户nacos权限后，nacos server 可以正常连接数据库启动。
```
# 如果用戶nacos没有权限，则用户授权访问
# GRANT ALL ON *.* TO 'nacos'@'%';

# 刷新权限
# flush privileges;
```

**Comment by paderlol** [comment]
你用的是例子的mysql镜像吗？我这边Mac没有出现这个问题

**Comment by toolsqacn** [comment]
MySQL镜像用的：image: nacos/nacos-mysql:5.7

**Comment by paderlol** [comment]
是第一次启动的时候吗？

**Comment by toolsqacn** [comment]
是的。使用 docker-compose -f example/standalone-mysql-5.7.yaml up

**Comment by paderlol** [comment]
我本地Mac环境没有出现，因为这个用户的创建是用的mysql镜像的官方，我并没有做其他处理
