### ISSUE TITLE
Nacos集群模式无法启动

### ISSUE THREAD

**Issue by eph6666** [nacos-group/nacos-docker#178]
环境：
kubernetes 1.19 in aws eks
mysql 5.7 aws rds

问题描述：
pod可以启动，但无正常启动的日志，
三个节点，有一个API返回Server down，另外两个无返回
进入容器 /home/nacos/logs/nacos.log
[nacos.log](https://github.com/nacos-group/nacos-docker/files/6301097/nacos.log)
显示如下报错

**Comment by paderlol** [comment]
自定义的数据库脚本需要提前初始化了

**Comment by eph6666** [comment]
已经初始化过数据库，tables已经创建

**Comment by paderlol** [comment]
看下naming server或者raft的日志，另外确认下cluster.domain是不是带了.

**Comment by eph6666** [comment]
Nacos 1.4.1
**naming-server.log：**
```
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)
2021-04-14 10:28:46,561 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: nacos-2.nacos-headless.nacos.svc.cluster.local:8848

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)
2021-04-14 10:28:48,562 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: nacos-1.nacos-headless.nacos.svc.cluster.local:8848
```

**Comment by eph6666** [comment]
**ENV:**
'''
JVM_XMN=1g
MODE=cluster
POD_NAMESPACE=nacos
HOSTNAME=nacos-0
NACOS_USER=nacos
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://172.20.0.1:443
TERM=xterm
KUBERNETES_SERVICE_PORT=443
JVM_MMS=320m
KUBERNETES_SERVICE_HOST=172.20.0.1
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
NACOS_APPLICATION_PORT=8848
NACOS_REPLICAS=3
DOMAIN_NAME=cluster.local
JVM_XMX=2g
JVM_XMS=2g
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
JAVA=/usr/lib/jvm/java-1.8.0-openjdk/bin/java
MYSQL_SERVICE_USER=admin
PWD=/home/nacos/logs
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
TIME_ZONE=Asia/Shanghai
SERVICE_NAME=nacos-headless
MYSQL_SERVICE_PASSWORD=*BcV!oQZrt_M3Qk3qWJUDQ9Qa
TOMCAT_ACCESSLOG_ENABLED=false
BASE_DIR=/home/nacos
NACOS_DEBUG=n
SHLVL=1
HOME=/root
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
NACOS_SERVER_PORT=8848
CLUSTER_CONF=/home/nacos/conf/cluster.conf
JVM_MS=128m
MYSQL_SERVICE_PORT=3306
CLASSPATH=.:/home/nacos/conf:
FUNCTION_MODE=all
KUBERNETES_PORT_443_TCP_ADDR=172.20.0.1
KUBERNETES_PORT_443_TCP=tcp://172.20.0.1:443
PREFER_HOST_MODE=hostname
MYSQL_SERVICE_HOST=mysql.cvvff5ytro8x.us-east-1.rds.amazonaws.com
MYSQL_SERVICE_DB_NAME=nacos
_=/usr/bin/env
OLDPWD=/home/nacos
'''

**Comment by paderlol** [comment]
试下用2.0.1镜像跑一下

**Comment by paderlol** [comment]
你日志里面显示你用的是2.0.0的版本 2.0.0需要打开grpc的端口 一共两个 一个是客户端的9848 另外一个是节点之间通讯的9849, 端口规则 是Nacos主端口+1000等于客户端端口 加1001等于grpc raft通讯端口.
具体规则自己去Nacos官网看下相关文档
