### ISSUE TITLE
MySQL 8.0  utf8mb4

### ISSUE THREAD

**Issue by chaiyd** [nacos-group/nacos-docker#187]
- 经过测试MySQL 8.0 库如果为utf8mb4 ,在一定情况下，会报下面的错误，但是现在又无法重现了
```
rg.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configOpsController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.3.0.jar!/com/alibaba/nacos/config/server/controller/ConfigOpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
```

**Comment by paderlol** [comment]
如果是数据库本身设置问题，可以自己更改，毕竟实际使用数据库都是自己的数据库。另外有可能使用镜像时数据库没启动完成Nacos镜像就已经启动了，这时候是无法找到数据库的

**Comment by chaiyd** [comment]
> 如果是数据库本身设置问题，可以自己更改，毕竟实际使用数据库都是自己的数据库。另外有可能使用镜像时数据库没启动完成Nacos镜像就已经启动了，这时候是无法找到数据库的

现在也只能先这样了，等复现了，在查看具体原因了
