### ISSUE TITLE
server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]

### ISSUE THREAD

**Issue by DuQingsong2002** [nacos-group/nacos-docker#200]
### 环境

- VMware Workstation16
- Centos 8
- Docker 20.10.7
- Nacos镜像 2.0.2
- Mysql 8

### 配置相关
192.168.213.128是虚拟机ip，192.168.43.31是主机ip，可以互通，无防火墙!
docker 
![K3%6 M P YM 2G TDX7`8`H](https://user-images.githubusercontent.com/59076088/126068411-7edeb364-e678-43f7-83a4-08eb453fc784.png)
![9XW602EVAYW0D5O2 08R@ A](https://user-images.githubusercontent.com/59076088/126068927-0a3ea359-275b-4e8e-a91e-507b8807290a.png)
![W_HF%DXYZAZRQ8`%I %7 NM](https://user-images.githubusercontent.com/59076088/126068930-ed286f47-8ec3-49f9-82ad-b6811b7ac57c.png)

---
![~$G`SWA_YXM6 9QN53$Y$F](https://user-images.githubusercontent.com/59076088/126068799-5bfd156a-e7cb-4fe8-a84b-5b8e71e692ae.png)

nginx
![PB`DL6HSY2SNB)2CI@Q8OSW](https://user-images.githubusercontent.com/59076088/126068520-2bac2243-42d6-4203-8acb-83e0ad01c035.png)

spring boot
![M5ZUN%X0ZP0R9ZG 2{J7S5V](https://user-images.githubusercontent.com/59076088/126068560-24d397a9-4710-43ec-a897-432d53cff840.png)

### 问题
浏览器访问正常
![9@@}J~RYNLHKKM`(@ `C` J](https://user-images.githubusercontent.com/59076088/126068607-1632eeb4-4329-4112-ae40-24506e445ecd.png)

程序报错👇

```
2021-07-18 20:49:18.058 ERROR [service-product,,] 22220 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, service-product register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='192.168.213.128:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='service-product', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.213.1', networkInterface='', port=8081, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}},

com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.213.128:8848]) tried: ErrCode:503, ErrMsg:server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:556) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212) ~[nacos-client-1.4.1.jar:na]
        ......
```
nacos.log👇
![5ON7PUQHE2}XE3((__$C~ E](https://user-images.githubusercontent.com/59076088/126068159-357ff3b2-9bf6-42b4-820d-d8acd5894864.png)

>

**Comment by paderlol** [comment]
grpc的端口没有放出来,2.0以后服务端grpc通讯端口等于主端口+1000, 这些在官方文档有说明,我的例子里面也有写

**Comment by DuQingsong2002** [comment]
> grpc的端口没有放出来,2.0以后服务端grpc通讯端口等于主端口+1000, 这些在官方文档有说明,我的例子里面也有写

ok了，谢谢！

**Comment by dotaZealot** [comment]
> grpc的端口没有放出来,2.0以后服务端grpc通讯端口等于主端口+1000, 这些在官方文档有说明,我的例子里面也有写

宝，k8s也遇到了这个问题，service、node均打开了+1000端口，还是不好使，能帮看看吗 @paderlol 
https://github.com/nacos-group/nacos-k8s/issues/358
