### ISSUE TITLE
[NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848

### ISSUE THREAD

**Issue by iamwak** [nacos-group/nacos-docker#211]
1. 镜像：nacos/nacos-server:1.4.1（nacos服务正常，可以正常登录web，编辑各项配置） 
2. 问题：启动jar包时已传参--server.path:nacos（jar程序容器启动时已传参--add-host=nacos:172.31.0.3），dubbo可以获取到此配置，但nacos.client.config却被强制设置为localhost，由于jar包与nacos为不同机器，故localhost获取到的本机无nacos导致jar包启动失败。

做过的尝试：

- 相同的jar包与nacos配置，不使用docker的情况下，jar包与nacos在不同机器可以启动成功，无异常。
- docker版nacos，传统方法部署java程序，问题依旧，报错信息一致。
- 传统方法部署nacos，docker版java程序，问题依旧，报错信息一致。
- 直接传参为IP（--server.path:172.31.0.3），问题依旧。

重点日志：

- dubbo可以获取到此配置

2021-09-24 16:18:38.651 [main] INFO  o.a.d.s.b.c.e.OverrideDubboConfigApplicationListener:68 - Dubbo Config was overridden by externalized configuration {dubbo.application.name=auth, dubbo.application.qos-enable=false, dubbo.cloud.subscribed-services=*, dubbo.config.multiple=true, dubbo.consumer.timeout=3000, dubbo.protocol.name=dubbo, dubbo.protocol.port=-1, dubbo.protocol.server=netty, dubbo.registry.address=nacos://nacos:8848, dubbo.scan.base-packages=com.aizhixin.dubbo}

- nacos.client.config却被强制设置为localhost

2021-09-24 16:18:38.725 [main] INFO  c.a.n.client.config.impl.LocalConfigInfoProcessor:212 - LOCAL_SNAPSHOT_PATH:/root/nacos/config
2021-09-24 16:18:38.830 [main] INFO  com.alibaba.nacos.client.config.impl.Limiter:54 - limitTime:5.0
2021-09-24 16:18:38.901 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)

------------------------------------------------------------------------------------------------------------------------------------
详细日志：
OpenJDK 64-Bit Server VM warning: MaxNewSize (1048576k) is equal to or greater than the entire heap (1048576k).  A new max generation size of 1048064k will be used.
2021-09-24 16:18:36.885 [main] INFO  org.apache.dubbo.common.logger.LoggerFactory:? - using logger: org.apache.dubbo.common.logger.slf4j.Slf4jLoggerAdapter
2021-09-24 16:18:36.911 [main] INFO  o.a.d.s.b.c.event.WelcomeLogoApplicationListener:63 - 

 :: Dubbo Spring Boot (v2.7.8) : https://github.com/apache/dubbo-spring-boot-project
 :: Dubbo (v2.7.8) : https://github.com/apache/dubbo
 :: Discuss group : dev@dubbo.apache.org

2021-09-24 16:18:36.920 [main] INFO  o.a.d.s.b.c.e.OverrideDubboConfigApplicationListener:68 - Dubbo Config was overridden by externalized configuration {dubbo.application.qos-enable=false, dubbo.config.multiple=true}
2021-09-24 16:18:38.500 [pool-1-thread-1] INFO  o.a.d.s.b.c.e.AwaitingNonWebApplicationListener:159 -  [Dubbo] Current Spring Boot Application is await...
2021-09-24 16:18:38.651 [main] INFO  o.a.d.s.b.c.e.OverrideDubboConfigApplicationListener:68 - Dubbo Config was overridden by externalized configuration {dubbo.application.name=auth, dubbo.application.qos-enable=false, dubbo.cloud.subscribed-services=*, dubbo.config.multiple=true, dubbo.consumer.timeout=3000, dubbo.protocol.name=dubbo, dubbo.protocol.port=-1, dubbo.protocol.server=netty, dubbo.registry.address=nacos://nacos:8848, dubbo.scan.base-packages=com.aizhixin.dubbo}

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.2.RELEASE)

2021-09-24 16:18:38.725 [main] INFO  c.a.n.client.config.impl.LocalConfigInfoProcessor:212 - LOCAL_SNAPSHOT_PATH:/root/nacos/config
2021-09-24 16:18:38.830 [main] INFO  com.alibaba.nacos.client.config.impl.Limiter:54 - limitTime:5.0
2021-09-24 16:18:38.901 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-09-24 16:18:39.057 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-09-24 16:18:39.258 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-09-24 16:18:39.458 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-09-24 16:18:39.464 [main] ERROR com.alibaba.nacos.client.config.impl.ClientWorker:279 - [fixed-localhost_8848] [sub-server] get server config exception, dataId=auth, group=DEFAULT_GROUP, tenant=
java.net.ConnectException: [NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:125)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:51)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:274)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:155)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:98)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:73)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:141)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:98)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.aizhixin.AuthApplication.main(AuthApplication.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
2021-09-24 16:18:39.466 [main] WARN  com.alibaba.nacos.client.config.NacosConfigService:166 - [fixed-localhost_8848] [get-config] get from server error, dataId=auth, group=DEFAULT_GROUP, tenant=, msg=ErrCode:500, ErrMsg:[NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
2021-09-24 16:18:39.467 [main] WARN  com.alibaba.nacos.client.config.NacosConfigService:170 - [fixed-localhost_8848] [get-config] get snapshot ok, dataId=auth, group=DEFAULT_GROUP, tenant=, config=
2021-09-24 16:18:39.469 [main] WARN  c.a.cloud.nacos.client.NacosPropertySourceBuilder:87 - Ignore the empty nacos configuration and get it based on dataId[auth] & group[DEFAULT_GROUP]
2021-09-24 16:18:39.472 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-09-24 16:18:39.673 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-09-24 16:18:39.873 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-09-24 16:18:40.073 [main] ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:109 - [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-09-24 16:18:40.074 [main] ERROR com.alibaba.nacos.client.config.impl.ClientWorker:279 - [fixed-localhost_8848] [sub-server] get server config exception, dataId=auth.properties, group=DEFAULT_GROUP, tenant=

**Comment by paderlol** [comment]
这个和用docker的Nacos应该没有关系，看起来是客户端拿到nacos的解析或者dubbo本身的解析主机名有问题

**Comment by iamwak** [comment]
> 这个和用docker的Nacos应该没有关系，看起来是客户端nacos的解析或者dubbo的解析主机名有问题

但是不使用docker，传统方式部署就不会有这个问题。
使用docker时，dubbo可以拿到自定义配置，而nacos.client.config获取到的配置却被强制为localhost。

**Comment by paderlol** [comment]
传统方法部署nacos，docker版java程序，问题依旧，报错信息一致。你自己都说了传统部署Nacos，docker部署java，那这个解析错误或者说问题肯定是发生在解析主机名对吧，跟server端没有任何关系呀

**Comment by iamwak** [comment]
> 传统方法部署nacos，docker版java程序，问题依旧，报错信息一致。你自己都说了传统部署Nacos，docker部署java，那这个解析错误或者说问题肯定是发生在解析主机名对吧，跟server端没有任何关系呀

可以正常解析，只是nacos.client.config获取不到自定义配置。

**Comment by iamwak** [comment]
> 传统方法部署nacos，docker版java程序，问题依旧，报错信息一致。你自己都说了传统部署Nacos，docker部署java，那这个解析错误或者说问题肯定是发生在解析主机名对吧，跟server端没有任何关系呀

请教下有没有哪种解决办法呢，遇到瓶颈了。

**Comment by paderlol** [comment]
可以暂时指定ip，然后是看下是不是client里面接收的时候有没有收到正确的host

**Comment by iamwak** [comment]
> 可以暂时指定ip，然后是看下是不是client里面接收的时候有没有收到正确的host

之前改过直接用ip，问题依旧，client还是接收不到正确的server地址，但是dubbo可以
