### ISSUE TITLE
nacos-docker集群部署好之后，用springcloud去注册服务报错 Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status

### ISSUE THREAD

**Issue by gholay** [nacos-group/nacos-docker#213]
正常使用docker启动了nacos集群版本，再使用springcloud nacos 2.0.1版本的client去连接docker版的nacos2.0.1 server服务器，竟然提示我安装的nacos服务器版本是1.x，报错信息如下:

> Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213) ~[nacos-client-2.0.1.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:101) ~[nacos-client-2.0.1.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) ~[nacos-client-2.0.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:139) ~[nacos-client-2.0.1.jar:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	... 20 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:205) ~[nacos-client-2.0.1.jar:na]

**Comment by paderlol** [comment]
你这个有可能原来的data目录下是否没有替换掉,导致里面有数据还1.x的
