### ISSUE TITLE
客户端总出现 longpolling error

### ISSUE THREAD

**Issue by lenonhere** [nacos-group/nacos-docker#216]
1. 操作系统

> macos big sur 11.6

2. IDE

> Intellij

3. nacos client

> 试过 1.4.1 、 1.4.2

4. nacos server

> 使用 docker 运行，运行脚本如下：

```
docker run --name nacos-quick -e MODE=standalone -p 9848:8848 -d nacos/nacos-server:latest
```

> 版本换过 1.3.2 、 1.4.1 、 2.0.2

5. 表现
> 项目启动后，能正常连接到 nacos ，授权、获取配置都正常，之后就开始出现 longpolling error ，每隔 12 秒左右出现一次。

6. 错误信息

> 不论 nacos client 及 nacos server 版本 各自为哪个，都会出现以下错误：

```
2021-10-19 16:54:37.020 [ERROR] 11551 [,/] [d-192.168.1.188_9848:516619] [c.a.n.client.config.impl.ClientWorker.run:580] longPolling error : 

java.io.IOException: Server returned HTTP response code: 502 for URL: http://192.168.1.188:9848/nacos/v1/cs/configs/listener
	at sun.reflect.GeneratedConstructorAccessor77.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getBody(JdkHttpClientResponse.java:64)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handleError(AbstractResponseHandler.java:51)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:44)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.postForm(NacosRestTemplate.java:407)
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:155)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:67)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:380)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:347)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:535)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: http://192.168.1.188:9848/nacos/v1/cs/configs/listener
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getStatusCode(JdkHttpClientResponse.java:79)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:43)
	... 14 common frames omitted
```
7. 其他补充

- debug 过 com.alibaba.nacos.client.config.http.ServerHttpAgent#httpPost 方法（也就是上述错误抛出的地方），将拿到的 header 、 body 拼装后，使用 postman 调用，表现为在30秒后返回 http code 200 （我理解为这是正常该有的表现）。

- 在 nacos docker 里，没找到关联的日志（502、longpolling搜索），不知是否是没有开启相关的错误日志。

- google 了一圈没有找到相关类似案例。

- 同事在 windows 底下运行，**没有**出现同样的错误。

不知是否有人能提供进一步排查的思路或线索，谢谢先~

**Comment by wechat361** [comment]
大佬，这个问题找到线索或解决了吗，我也遇到同样问题了，求解
