### ISSUE TITLE
M1 下真的可以运行成功吗？

### ISSUE THREAD

**Issue by jsonchou** [nacos-group/nacos-docker#281]
### 配置环境：
- **nacos/nacos-server:v2.1.1-slim**

``` yml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:v2.1.1-slim
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
```

### 修改链接、超时时间：

MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=**10000**&socketTimeout=**30000**&autoReconnect=true&useSSL=false&serverTimezone=**Asia/Shanghai**

以上配置，全都无法正常运行。

### 报错  "No DataSource set"

Nacos 2.1.1
Running in stand alone mode, All function modules
Port: 8848
Console: http://**07eb20515a96**:8848/nacos/index.html **貌似没有获取到主机ip？**

``` java
mysql                   | runtime: failed to create new OS thread (have 2 already; errno=22)
mysql                   | fatal error: newosproc
mysql                   | 
mysql                   | runtime stack:
mysql                   | runtime.throw(0x524da0, 0x9)
mysql                   |       /usr/local/go/src/runtime/panic.go:527 +0x90
mysql                   | runtime.newosproc(0xc82002a000, 0xc820039fc0)
mysql                   |       /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
mysql                   | runtime.newm(0x555ce8, 0x0)
mysql                   |       /usr/local/go/src/runtime/proc1.go:1105 +0x130
mysql                   | runtime.main.func1()
mysql                   |       /usr/local/go/src/runtime/proc.go:48 +0x2c
mysql                   | runtime.systemstack(0x5c4300)
mysql                   |       /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
mysql                   | runtime.mstart()
mysql                   |       /usr/local/go/src/runtime/proc1.go:674
mysql                   | 
mysql                   | goroutine 1 [running]:
mysql                   | runtime.systemstack_switch()
mysql                   |       /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820024770 sp=0xc820024768
mysql                   | runtime.main()
mysql                   |       /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200247c0 sp=0xc820024770
mysql                   | runtime.goexit()
mysql                   |       /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200247c8 sp=0xc8200247c0
mysql exited with code 2
```

``` java
nacos-standalone-mysql  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
nacos-standalone-mysql  |       at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
nacos-standalone-mysql  |       ... 42 common frames omitted
nacos-standalone-mysql  | Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
nacos-standalone-mysql  |       at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:225)
nacos-standalone-mysql  |       at com.alibaba.nacos.config.server.service.dump.ExternalDumpService.init(ExternalDumpService.java:52)
nacos-standalone-mysql  |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos-standalone-mysql  |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos-standalone-mysql  |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos-standalone-mysql  |       at java.lang.reflect.Method.invoke(Method.java:498)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
nacos-standalone-mysql  |       ... 54 common frames omitted
nacos-standalone-mysql  | Caused by: java.lang.IllegalStateException: No DataSource set
```

### 硬件环境：
Apple M1 Max

**Comment by jsonchou** [comment]
目前看来，只有这一种方式可行，M1下，唯一可运行成功的，只有这一种方式：

``` bash
docker pull zhusaidong/nacos-server-m1:2.0.3
docker run --name nacos-standalone -e MODE=standalone -e JVM_XMS=512m -e JVM_XMX=512m -e JVM_XMN=256m -p 8848:8848 -d zhusaidong/nacos-server-m1:2.0.3
```
