### ISSUE TITLE
2.2.3 部署nacos集群是否不能设置为embedded存储模式

### ISSUE THREAD

**Issue by billyyoyo** [nacos-group/nacos-docker#395]
部署nacos集群是否不能设置为embedded存储模式，用mysql一切正常

根据nacose-ip.yml修改：
#nacos dev env
NACOS_SERVERS=172.16.238.10:8848 172.16.238.11:8848 172.16.238.12:8848
NACOS_AUTH_ENABLE=true
EMBEDDED_STORAGE=embedded                                                                                                                                                                                         
#SPRING_DATASOURCE_PLATFORM=mysql
#MYSQL_SERVICE_HOST=172.100.0.1
#MYSQL_SERVICE_DB_NAME=nacos
#MYSQL_SERVICE_PORT=3306
#MYSQL_SERVICE_USER=xxxx
#MYSQL_SERVICE_PASSWORD=xxxx
#MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
NACOS_AUTH_IDENTITY_KEY=2222
NACOS_AUTH_IDENTITY_VALUE=2xxx
NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789

nacos.log
Caused by: com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 500, errMsg: java.lang.NullPointerException
	at com.alibaba.nacos.config.server.service.repository.embedded.DistributedDatabaseOperateImpl.queryOne(DistributedDatabaseOperateImpl.java:237)

protocol-raft.log
2024-03-08 16:41:15,515 ERROR Failed to join the cluster, retry...
java.lang.IllegalStateException: Fail to get leader of group nacos_config, Unknown leader, Unknown leader, Unknown leader
    at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:605)

**Comment by freemankevin** [comment]
有同样的疑问：
```shell
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'basicAuthenticationFilter' defined in class path resource [com/alibaba/nacos/prometheus/filter/PrometheusAuthFilter.class]: Unsatisfied dependency expressed through method 'basicAuthenticationFilter' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthConfig' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/default-auth-plugin-2.3.0.jar!/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosUserDetailsServiceImpl': Unsatisfied dependency expressed through field 'userPersistService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalUserPersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error

```

**Comment by secbr** [comment]
> 部署nacos集群是否不能设置为embedded存储模式，用mysql一切正常
> 
> 根据nacose-ip.yml修改： #nacos dev env NACOS_SERVERS=172.16.238.10:8848 172.16.238.11:8848 172.16.238.12:8848 NACOS_AUTH_ENABLE=true EMBEDDED_STORAGE=embedded #SPRING_DATASOURCE_PLATFORM=mysql #MYSQL_SERVICE_HOST=172.100.0.1 #MYSQL_SERVICE_DB_NAME=nacos #MYSQL_SERVICE_PORT=3306 #MYSQL_SERVICE_USER=xxxx #MYSQL_SERVICE_PASSWORD=xxxx #MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true NACOS_AUTH_IDENTITY_KEY=2222 NACOS_AUTH_IDENTITY_VALUE=2xxx NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
> 
> nacos.log Caused by: com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 500, errMsg: java.lang.NullPointerException at com.alibaba.nacos.config.server.service.repository.embedded.DistributedDatabaseOperateImpl.queryOne(DistributedDatabaseOperateImpl.java:237)
> 
> protocol-raft.log 2024-03-08 16:41:15,515 ERROR Failed to join the cluster, retry... java.lang.IllegalStateException: Fail to get leader of group nacos_config, Unknown leader, Unknown leader, Unknown leader at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:605)

实测通过embedded存储模式可以实现集群的功能，注意基于内嵌数据库存在的启动命令为：
`sh startup.sh -p embedded`，其中参数是`-p`而不是`-m`

**Comment by secbr** [comment]
> 有同样的疑问：
> 
> ```shell
> org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
>         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165)
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
>         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
>         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
>         at com.alibaba.nacos.Nacos.main(Nacos.java:48)
> ...
> Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'basicAuthenticationFilter' defined in class path resource [com/alibaba/nacos/prometheus/filter/PrometheusAuthFilter.class]: Unsatisfied dependency expressed through method 'basicAuthenticationFilter' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthConfig' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/default-auth-plugin-2.3.0.jar!/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosUserDetailsServiceImpl': Unsatisfied dependency expressed through field 'userPersistService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalUserPersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
> ```

实测通过embedded存储模式可以实现集群的功能，注意基于内嵌数据库存在的启动命令为：
`sh startup.sh -p embedded`，其中参数是`-p`而不是`-m`

**Comment by jiangsikai** [comment]
请问解决了吗？ 我也遇到同样问题

PREFER_HOST_MODE=hostname
EMBEDDED_STORAGE=embedded
NACOS_SERVERS=10.1.10.39:8848 10.1.100.38:8849 10.1.100.44:8850
#SPRING_DATASOURCE_PLATFORM=mysql
#MYSQL_SERVICE_DB_NAME=nacos_devtest
#MYSQL_SERVICE_PORT=3306
#MYSQL_SERVICE_USER=nacos
#MYSQL_SERVICE_PASSWORD=nacos
NACOS_AUTH_IDENTITY_KEY=2222
NACOS_AUTH_IDENTITY_VALUE=2xxx
NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789


java.lang.IllegalStateException: Fail to get leader of group nacos_config, Unknown leader, Fail to find node 10.1.100.44:7850 in group nacos_config, null, Fail to find node 10.1.100.38:7849 in group nacos_config
        at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:605)
        at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:498)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.registerSelfToCluster(JRaftServer.java:353)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$0(JRaftServer.java:264)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by jiangsikai** [comment]
> embedded
实测通过embedded存储模式可以实现集群的功能，注意基于内嵌数据库存在的启动命令为：
sh startup.sh -p embedded，其中参数是-p而不是-m   

请问怎么解决的？

**Comment by paderlol** [comment]
fixed
