### ISSUE TITLE
镜像环境变量及启动脚本设计缺陷

### ISSUE THREAD

**Issue by Shiyajian** [nacos-group/nacos-docker#40]
1、这是最新的docker镜像内部的application.properties文件，可以看到以下问题：
```
server.servlet.contextPath=${SERVER_SERVLET_CONTEXTPATH:/nacos}
server.contextPath=/nacos
server.port=${NACOS_SERVER_PORT:8848}
spring.datasource.platform=${SPRING_DATASOURCE_PLATFORM:""}
nacos.cmdb.dumpTaskInterval=3600
nacos.cmdb.eventTaskInterval=10
nacos.cmdb.labelTaskInterval=300
nacos.cmdb.loadDataAtStart=false
db.num=2
db.url.0=jdbc:mysql://${MYSQL_MASTER_SERVICE_HOST}:${MYSQL_MASTER_SERVICE_PORT:3306}/${MYSQL_MASTER_SERVICE_DB_NAME}?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.url.1=jdbc:mysql://${MYSQL_SLAVE_SERVICE_HOST}:${MYSQL_SLAVE_SERVICE_PORT:3306}/${MYSQL_MASTER_SERVICE_DB_NAME}?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=${MYSQL_MASTER_SERVICE_USER}
db.password=${MYSQL_MASTER_SERVICE_PASSWORD}
```
- 必须填写MASTER和SLAVE两个数据源信息，num数量不可修改，虽然可以通过两个数据源地址一致实现启动，但是设计不太合理；
- SLAVE只有 HOST 和 PORT参数，默认设计是 MASTER 和 SLAVE 是同用户和同密码吗？如果是的话，那这db.user和db.password的key应该 MYSQL_SERVICE_USER，而不应该加上_MASTER_？

2、docker 启动脚本存在设计缺陷，启动后会卡住当前 ssh session ,control + c也没办法退出，只能关闭当前session重新打开

**Comment by paderlol** [comment]
非常感谢你的意见，我会进行改进，如果比较好的改进也欢迎提PR

**Comment by jiangchunliang** [comment]
我也发现了这个问题，我重新构建了镜像，运行起来了，但是发现客户端注册不进去提示 503 server is DOWN now, please try again later!
在日志下发现这个异常：
java.lang.IllegalArgumentException: server: dcf0a2fd9b78-nacos1:8848 is not in serverlist
  at com.alibaba.nacos.naming.cluster.ServerListManager.onReceiveServerStatus(ServerListManager.java:196)
  at com.alibaba.nacos.naming.cluster.ServerListManager$ServerStatusReporter.run(ServerListManager.java:415)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
2019-07-09 18:06:59,662 INFO receive config info: unknown#dcf0a2fd9b78-nacos1:8848#1562666819662#2

**Comment by paderlol** [comment]
你这个似乎不是镜像的问题,而是你的运行配置的问题,可以发下你的配置出来看下,你这个问题和他的不是一个问题呢

**Comment by paderlol** [comment]
建议重新提个issue,这个issue的问题已经解决了,所以我close掉了
