### ISSUE TITLE
nacos latest+mysql8.0.16 Unknown system variable 'tx_read_only'

### ISSUE THREAD

**Issue by hb0730** [nacos-group/nacos-docker#56]
我在做nacos 单机 单独使用mysql时报
```
2019-09-19 14:12:26,825 WARN Failure in @ExceptionHandler public void com.alibaba.nacos.config.server.exception.GlobalExceptionHandler.handleDataAccessException(javax.servlet.http.HttpServletResponse,org.springframework.dao.DataAccessException) throws org.springframework.dao.DataAccessException

org.springframework.jdbc.CannotGetJdbcConnectionException: PreparedStatementCallback; Could not retrieve transation read-only status server; nested exception is java.sql.SQLException: Could not retrieve transation read-only status server
        at com.alibaba.nacos.config.server.exception.GlobalExceptionHandler.handleDataAccessException(GlobalExceptionHandler.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:408)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:61)
        at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:136)
        at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80)
        at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1297)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1109)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.config.server.filter.NacosWebFilter.doFilter(NacosWebFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2019-09-19 14:12:26,827 ERROR Servlet.service() for servlet [dispatcherServlet] in context with path [/nacos] threw exception [Request processing failed; nested exception is org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; Could not retrieve transation read-only status server; nested exception is java.sql.SQLException: Could not retrieve transation read-only status server] with root cause

java.sql.SQLException: Unknown system variable 'tx_read_only'
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
        at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3601)
        at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3576)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2107)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.springframework.jdbc.core.JdbcTemplate.lambda$update$1(JdbcTemplate.java:894)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:893)
        at com.alibaba.nacos.config.server.service.PersistService.addConfigInfoAtomic(PersistService.java:2700)
        at com.alibaba.nacos.config.server.service.PersistService.access$000(PersistService.java:68)
        at com.alibaba.nacos.config.server.service.PersistService$1.doInTransaction(PersistService.java:507)
        at com.alibaba.nacos.config.server.service.PersistService$1.doInTransaction(PersistService.java:503)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at com.alibaba.nacos.config.server.service.PersistService.addConfigInfo(PersistService.java:503)
        at com.alibaba.nacos.config.server.service.PersistService.batchInsertOrUpdate(PersistService.java:3502)
        at com.alibaba.nacos.config.server.service.PersistService$$FastClassBySpringCGLIB$$21ae4232.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at com.alibaba.nacos.config.server.service.PersistService$$EnhancerBySpringCGLIB$$30703887.batchInsertOrUpdate(<generated>)
        at com.alibaba.nacos.config.server.controller.ConfigController.importAndPublishConfig(ConfigController.java:542)
        at com.alibaba.nacos.config.server.controller.ConfigController$$FastClassBySpringCGLIB$$dbb89c38.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at com.alibaba.nacos.config.server.controller.ConfigController$$EnhancerBySpringCGLIB$$8fbeb6c1.importAndPublishConfig(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.config.server.filter.NacosWebFilter.doFilter(NacosWebFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2019-09-19 14:12:26,828 ERROR Responding with unauthorized error. Message - Full authentication is required to access this resource
```
## docker-compose.yml
```
version: '3.1'
services:
   nacos:
     image: nacos/nacos-server
     container_name: nacos
     environment:
       - PREFER_HOST_MODE=ip
       - MODE=standalone
       - SPRING_DATASOURCE_PLATFORM=mysql
       - MYSQL_MASTER_SERVICE_HOST=172.24.151.254
       - MYSQL_MASTER_SERVICE_DB_NAME=nacos_config
       - MYSQL_MASTER_SERVICE_PORT=3306
       - MYSQL_MASTER_SERVICE_USER=root
       - MYSQL_MASTER_SERVICE_PASSWORD=Admin123
       - MYSQL_SLAVE_SERVICE_HOST=172.24.151.254
       - MYSQL_SLAVE_SERVICE_PORT=3306
     volumes:
       - ./data/log/standalone-logs/:/home/nacos/logs
       - ./data/init.d/custom.properties:/home/nacos/init.d/custom.properties
     ports:
       - "8848:8848"
```
请问是否nacos 支持mysql8.x以上版本，该如何部署

**Comment by jaybrilgrace** [comment]
the same question in my project

**Comment by paderlol** [comment]
Nacos如果要使用mysql8,需要把mysql8的driver包替换到plugin的mysql目录，具体可以去看下官方文档…默认只支持mysql5

**Comment by paderlol** [comment]
可以挂卷出来，挂mysql8的驱动包到/home/nacos/plugin/mysql下面

**Comment by hb0730** [comment]
@paderlol 请问什么版本会支持mysql8，有计划吗，
挂卷方式：好的，我试试

**Comment by hb0730** [comment]
@paderlol 好的，我会尽快试试

**Comment by jaybrilgrace** [comment]
> 已经支持了啊…需要替换驱动包就是nacos提供的方式…因为5和8的驱动不兼容

我用的是阿里云的8.0数据库，也出现现在的问题，应该怎么修改呢

**Comment by hb0730** [comment]
> > 已经支持了啊......需要替换驱动包就是NACOS提供的方式...因为5和8的驱动不兼容
> 
> 我用的是阿里云的8.0数据库，也出现现在的问题，应该怎么修改呢
https://github.com/nacos-group/nacos-docker/issues/56#issuecomment-534124444

**Comment by paderlol** [comment]
@hb0730 跟上面的一样，这个是驱动问题…并不是你用哪个服务商的数据库的问题。

**Comment by hb0730** [comment]
@paderlol 这个问题确实是版本问题,现按照你说的做了，貌似并未生效,
![image](https://user-images.githubusercontent.com/33956166/65473538-cc01fe00-deaa-11e9-81dd-404bab007b4a.png)
![image](https://user-images.githubusercontent.com/33956166/65473562-f05dda80-deaa-11e9-9da5-a1295370a0b7.png)
![image](https://user-images.githubusercontent.com/33956166/65473596-079cc800-deab-11e9-862c-2131e42fecc4.png)

**Comment by hb0730** [comment]
@paderlol 期待解决这个问题

**Comment by jaybrilgrace** [comment]
啥时候能解决呢？等着上生产

**Comment by paderlol** [comment]
已经解决了，最新镜像已经解决这个问题了，要怎么使用，请参照上面的对话。

**Comment by jaybrilgrace** [comment]
@paderlol 
是修改这个配置wen文件吗？

![image](https://user-images.githubusercontent.com/43530470/65485295-13e94b00-ded4-11e9-9942-d16bfc071bf8.png)

**Comment by paderlol** [comment]
这个是修复问题的commit，可以挂卷出来，挂mysql8的驱动包到/home/nacos/plugins/mysql 
下面

**Comment by jaybrilgrace** [comment]
@paderlol 意思是我需要把mysql8的jar传到/home/nacos/plugins/mysql下面咯

**Comment by jaybrilgrace** [comment]
@paderlol 感觉说的不是很清楚，大佬能把完整的fix流程列一下么。万分感谢

**Comment by paderlol** [comment]
是的，把驱动包挂载进去…这个实现在nacos 1.0就有了，这边docker修复只是把启动过程中加载这个驱动包来达到应用能找到驱动相关的class，利用的extclassloader

**Comment by jaybrilgrace** [comment]
@hb0730 我看下了容器里的路径，根本没有data/lib 你这样挂，肯定是不行的吧
![image](https://user-images.githubusercontent.com/43530470/65487128-c7543e80-ded8-11e9-8146-be653a278e64.png)

**Comment by paderlol** [comment]
前面是宿主机，后面是容器路径。

**Comment by hb0730** [comment]
@jaybrilgrace 我这样是吧驱动包挂载进`/home/nacos/plugin/mysql`,这样是没有问题的，我已经试过

**Comment by jaybrilgrace** [comment]
@hb0730 就截图那样挂载？

**Comment by paderlol** [comment]
plugins

**Comment by hb0730** [comment]
@jaybrilgrace  只不过你的驱动包要放在`./data/lib`下，启动之后你可以`docker exec -it xxx /bin/bash`查看你的驱动包是否进去了，

**Comment by hb0730** [comment]
容器挂载路径:`/home/nacos/plugins/mysql`

**Comment by jaybrilgrace** [comment]
@hb0730 ./data/lib这个路径是容器里的路径吗？还是在下面t图里的增加一个data文件夹，然后把jar放进去？
![image](https://user-images.githubusercontent.com/43530470/65487541-ad672b80-ded9-11e9-9e21-e7ef14eff535.png)

**Comment by hb0730** [comment]
@jaybrilgrace `./data/lib`宿主机的
docker中 一般是左边宿主机右边容器的

**Comment by jaybrilgrace** [comment]
@hb0730 那就是要在宿主机里建/data/lib这个文件夹，把jar包放进去咯

**Comment by jaybrilgrace** [comment]
@hb0730 这样对吗
![image](https://user-images.githubusercontent.com/43530470/65487935-8826ed00-deda-11e9-8e67-99de661ec2f0.png)

**Comment by hb0730** [comment]
@jaybrilgrace 是的，其实左边的宿主机您自己可以自定义的，只要能挂载进容器的指定位置就行

**Comment by jaybrilgrace** [comment]
@hb0730 挂载进去了 但还是报错哦

**Comment by hb0730** [comment]
@jaybrilgrace 我是成功的
@paderlol 感谢，以及可以导入导出配置中心的文件了

**Comment by hb0730** [comment]
@jaybrilgrace 您可以进入容器查看是否挂载成功，

**Comment by jaybrilgrace** [comment]
@paderlol 还是这样的错误
![image](https://user-images.githubusercontent.com/43530470/65488461-c670dc00-dedb-11e9-83b7-ea32fc77f44d.png)

**Comment by jaybrilgrace** [comment]
@hb0730 挂载成功了 在容器里已经有了
![image](https://user-images.githubusercontent.com/43530470/65488869-8bbb7380-dedc-11e9-80e7-5a5928b5a686.png)

**Comment by paderlol** [comment]
确保自己的镜像是最新的，我今天上午重新构建的镜像

**Comment by jaybrilgrace** [comment]
> 确保自己的镜像是最新的，我今天上午重新构建的镜像

感谢大佬，真的需要最新的镜像
太坑了~
