### ISSUE TITLE
最新master分支上的单机带MySQL版启动失败

### ISSUE THREAD

**Issue by zzhujing** [nacos-group/nacos-docker#85]
使用`standalone-mysql-8.yml`的docker-compose启动之后出现如下错误
- `docker-compose.yml`
```yaml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
```
- 错误信息：
```java
Caused by: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
        at com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl.init(BasicDataSourceServiceImpl.java:134)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
```

**Comment by paderlol** [comment]
很有可能是第一次启动导致的 因为数据库没有初始化完成nacos就启动了,而且这个情况就是出现在mysql8的镜像

**Comment by paderlol** [comment]
重新启动一次就可以了

**Comment by zzhujing** [comment]
@paderlol 您好，我按您的方式尝试过了。还是没起作用呢。然后我使用5.7的也失败了。失败的堆栈信息如下
```java
java.io.IOException: java.lang.IllegalArgumentException: Could not resolve placeholder 'MYSQL_MASTER_SERVICE_HOST' in value "jdbc:mysql://${MYSQL_MASTER_SERVICE_HOST}:${MYSQL_MASTER_SERVICE_PORT:3306}/${MYSQL_MASTER_SERVICE_DB_NAME}?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true"
        at com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl.reload(BasicDataSourceServiceImpl.java:217)
        at com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl.init(BasicDataSourceServiceImpl.java:131)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by paderlol** [comment]
1.1.4或者以下版本 不要用master分支,选择对应的分支

**Comment by zzhujing** [comment]
@paderlol 谢谢您的解答，之前拉取的latest版本过低，现在改成nacos/nacos-server:1.2.0 解决了我的问题
